name: Build and Release

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  calculate-version:
    name: Calculate Version
    runs-on: ubuntu-latest
    outputs:
      semVer: ${{ steps.gitversion.outputs.fullSemVer }}
    steps:
      - uses: actions/checkout@v3
        name: Checkout code
        with:
          fetch-depth: 0

      - uses: gittools/actions/gitversion/setup@v0.9.7
        name: Install GitVersion
        with:
          versionSpec: '5.x'

      - uses: gittools/actions/gitversion/execute@v0.9.7
        name: Determine Version
        id: gitversion
        with:
          useConfigFile: true
          configFilePath: gitversion.yml

  build_windows:
    name: Build for Windows
    runs-on: windows-latest
    needs: calculate-version
    steps:
      - uses: actions/checkout@v3
        name: Checkout code

      - uses: actions/setup-go@v3
        name: Install Go
        with:
          go-version: '>=1.18.0'

      - name: Build project
        run: |
          go build
          ls
      - uses: actions/upload-artifact@v3
        name: Upload artifact
        with:
          name: test-app-${{ needs.calculate-version.outputs.semVer }}
          path: ado-tokens.exe

  build_linux:
    name: Build for Linux
    runs-on: ubuntu-latest
    needs: calculate-version
    steps:
      - uses: actions/checkout@v3
        name: Checkout code

      - uses: actions/setup-go@v3
        name: Install Go
        with:
          go-version: '>=1.18.0'

      - name: Build project
        run: |
          go build
          ls
      - uses: actions/upload-artifact@v3
        name: Upload artifact
        with:
          name: test-app-${{ needs.calculate-version.outputs.semVer }}
          path: ado-tokens

  release:
    name: Release
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    needs:
      - calculate-version
      - build_windows
      - build_linux
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: test-app-${{ needs.calculate-version.outputs.semVer }}

      - uses: ncipollo/release-action@v1
        name: Create release
        if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/heads/support/')
        with:
          artifacts: ado-tokens.exe
          tag: ${{ needs.calculate-version.outputs.semVer }}
          omitBody: true
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false

      - uses: ncipollo/release-action@v1
        name: Create pre-release
        if: github.ref != 'refs/heads/master' && !(startsWith(github.ref, 'refs/heads/support/'))
        with:
          artifacts: ado-tokens.exe
          tag: ${{ needs.calculate-version.outputs.semVer }}
          omitBody: true
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true